### ISSUE TITLE
add `skip_decompress` to target definition in YAML, and avoid decompression if `true`

### ISSUE THREAD

**Issue by jondot** [rusty-ferris-club/rustwrap#1]
example (notice the win32 link):

```
targets:
    - platform: win32
      arch: x64
      url_template: https://github.com/lycheeverse/lychee/releases/download/v0.10.3/lychee-v0.10.3-windows-x86_64.exe
    - platform: linux
      arch: x64
      url_template: https://github.com/lycheeverse/lychee/releases/download/v0.10.3/lychee-v0.10.3-x86_64-unknown-linux-gnu.tar.gz
    # - platform: darwin
    #   arch: x64
    #   url_template: https://github.com/lycheeverse/lychee/releases/download/v0.10.3/lychee-v0.10.3-macos-x86_64.dmg
    - platform: darwin
      arch: x64
      url_template: https://github.com/lycheeverse/lychee/releases/download/v0.10.3/lychee-v0.10.3-aarch64-unknown-linux-gnu.tar.gz
```

Auto-detecting if decompress needed is also OK.
